# Generated by Django 5.2.4 on 2025-08-18 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='extra_phone',
            field=models.CharField(default=0, max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='home_phone',
            field=models.CharField(default=0, max_length=150),
        ),
    ]
