# Generated by Django 5.2.4 on 2025-10-30 03:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_extra_phone_user_home_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default=0, max_length=150, validators=[django.core.validators.RegexValidator(message='Telefon raqam 998 bilan boshlanib, jami 12 ta raqamdan iborat bo‘lishi kerak (masalan: 998935472697).', regex='^998\\d{9}$')]),
        ),
    ]
