version: '3.8'

services:
  davomat:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
    command: >
      bash -c "
        python3 manage.py migrate &&
        python3 manage.py collectstatic --noinput &&
        gunicorn -w 4 -b 0.0.0.0:8000 davomat.wsgi
      "
    volumes:
      - .:/app
    ports:
      - "3012:8000"
    env_file:
      - .env
    environment:
      - TZ=Asia/Tashkent
    restart: always

  bot:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
    command: python3 bot/run.py
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles
    env_file:
      - .env
    environment:
      - TZ=Asia/Tashkent
    restart: always
