# Generated by Django 5.2.4 on 2025-08-18 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_is_active_task_is_deleted_alter_task_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('decree', 'Фармон/Қарор'), ('law', 'Қонун'), ('article', 'Мақола'), ('other', 'Бошқа')], default='other', max_length=50, verbose_name='Ҳужжат тури')),
                ('title', models.CharField(max_length=255, verbose_name='Янгилик сарлавҳаси')),
                ('summary', models.TextField(verbose_name='Қисқа мазмун')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Ссылка')),
                ('document_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Янгилик',
                'verbose_name_plural': 'Янгиликлар',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Qisqa matn')),
                ('description', models.TextField(blank=True, null=True, verbose_name='To‘liq matn')),
                ('alert_date', models.DateField(verbose_name='Ogohlantirish sanasi')),
                ('repeat_type', models.CharField(choices=[('none', 'Qaytmaydi'), ('daily', 'Kunlik'), ('weekly', 'Haftalik'), ('monthly', 'Oylik'), ('yearly', 'Yillik')], default='none', max_length=10, verbose_name='Qaytarilish turi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='ministrytree',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='ministrytree',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.CreateModel(
            name='Distance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.attendance')),
            ],
        ),
        migrations.CreateModel(
            name='NewsMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Расм'), ('video', 'Видео'), ('file', 'file')], max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='news/media/')),
                ('url', models.URLField(blank=True, null=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='tasks.news')),
            ],
            options={
                'verbose_name': 'Янгилик медиа',
                'verbose_name_plural': 'Янгилик медиа файллари',
            },
        ),
    ]
