# Generated by Django 5.2.4 on 2025-10-29 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_news_reminder_ministrytree_latitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ministrytree',
            old_name='name',
            new_name='name_uz',
        ),
        migrations.AddField(
            model_name='ministrytree',
            name='name_cr',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='ministrytree',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='children', to='tasks.ministrytree'),
        ),
    ]
