# Generated by Django 5.2.4 on 2025-10-30 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_rename_name_ministrytree_name_uz_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ministrytree',
            old_name='name_uz',
            new_name='name',
        ),
    ]
