# Generated by Django 5.2.4 on 2026-01-06 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_rename_name_uz_ministrytree_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='info_type',
            field=models.CharField(blank=True, choices=[('attendance', 'Attendance'), ('information', 'Information')], default='attendance', max_length=20, null=True),
        ),
    ]
